/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MonitoramentoRouteImport } from './routes/monitoramento'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as IndexRouteImport } from './routes/index'

const MonitoramentoRoute = MonitoramentoRouteImport.update({
  id: '/monitoramento',
  path: '/monitoramento',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/historico': typeof HistoricoRoute
  '/monitoramento': typeof MonitoramentoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/historico': typeof HistoricoRoute
  '/monitoramento': typeof MonitoramentoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/historico': typeof HistoricoRoute
  '/monitoramento': typeof MonitoramentoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/alertas' | '/historico' | '/monitoramento'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/alertas' | '/historico' | '/monitoramento'
  id: '__root__' | '/' | '/alertas' | '/historico' | '/monitoramento'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertasRoute: typeof AlertasRoute
  HistoricoRoute: typeof HistoricoRoute
  MonitoramentoRoute: typeof MonitoramentoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/monitoramento': {
      id: '/monitoramento'
      path: '/monitoramento'
      fullPath: '/monitoramento'
      preLoaderRoute: typeof MonitoramentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertasRoute: AlertasRoute,
  HistoricoRoute: HistoricoRoute,
  MonitoramentoRoute: MonitoramentoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
